# Minimal Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: rainbow waves, by azurepolarbear
description: azurepolarbear's rainbow waves algorithmic art project
logo: "https://azurepolarbear.github.io/assets/img/logo.png"
show_downloads: false
